/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniesRouteImport } from './routes/testimonies'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as LiveRouteImport } from './routes/live'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimoniesRouteImport } from './routes/admin.testimonies'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSermonsRouteImport } from './routes/admin.sermons'
import { Route as AdminPrayerRequestsRouteImport } from './routes/admin.prayer-requests'
import { Route as AdminMinistriesRouteImport } from './routes/admin.ministries'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLiveStreamRouteImport } from './routes/admin.live-stream'
import { Route as AdminLeadersRouteImport } from './routes/admin.leaders'
import { Route as AdminHeroSlidesRouteImport } from './routes/admin.hero-slides'
import { Route as AdminGivingRouteImport } from './routes/admin.giving'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'

const TestimoniesRoute = TestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniesRoute = AdminTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerRequestsRoute = AdminPrayerRequestsRouteImport.update({
  id: '/prayer-requests',
  path: '/prayer-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinistriesRoute = AdminMinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveStreamRoute = AdminLiveStreamRouteImport.update({
  id: '/live-stream',
  path: '/live-stream',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadersRoute = AdminLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroSlidesRoute = AdminHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGivingRoute = AdminGivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/live-stream': typeof AdminLiveStreamRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/live-stream': typeof AdminLiveStreamRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/live-stream': typeof AdminLiveStreamRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/prayer-requests': typeof AdminPrayerRequestsRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonies': typeof AdminTestimoniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/hero-slides'
    | '/admin/leaders'
    | '/admin/live-stream'
    | '/admin/messages'
    | '/admin/ministries'
    | '/admin/prayer-requests'
    | '/admin/sermons'
    | '/admin/subscribers'
    | '/admin/testimonies'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/hero-slides'
    | '/admin/leaders'
    | '/admin/live-stream'
    | '/admin/messages'
    | '/admin/ministries'
    | '/admin/prayer-requests'
    | '/admin/sermons'
    | '/admin/subscribers'
    | '/admin/testimonies'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/sermons'
    | '/testimonies'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/giving'
    | '/admin/hero-slides'
    | '/admin/leaders'
    | '/admin/live-stream'
    | '/admin/messages'
    | '/admin/ministries'
    | '/admin/prayer-requests'
    | '/admin/sermons'
    | '/admin/subscribers'
    | '/admin/testimonies'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  GivingRoute: typeof GivingRoute
  LiveRoute: typeof LiveRoute
  MinistriesRoute: typeof MinistriesRoute
  PrayerRoute: typeof PrayerRoute
  SermonsRoute: typeof SermonsRoute
  TestimoniesRoute: typeof TestimoniesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonies': {
      id: '/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof TestimoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonies': {
      id: '/admin/testimonies'
      path: '/testimonies'
      fullPath: '/admin/testimonies'
      preLoaderRoute: typeof AdminTestimoniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer-requests': {
      id: '/admin/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/admin/prayer-requests'
      preLoaderRoute: typeof AdminPrayerRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ministries': {
      id: '/admin/ministries'
      path: '/ministries'
      fullPath: '/admin/ministries'
      preLoaderRoute: typeof AdminMinistriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-stream': {
      id: '/admin/live-stream'
      path: '/live-stream'
      fullPath: '/admin/live-stream'
      preLoaderRoute: typeof AdminLiveStreamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaders': {
      id: '/admin/leaders'
      path: '/leaders'
      fullPath: '/admin/leaders'
      preLoaderRoute: typeof AdminLeadersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero-slides': {
      id: '/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AdminHeroSlidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/giving': {
      id: '/admin/giving'
      path: '/giving'
      fullPath: '/admin/giving'
      preLoaderRoute: typeof AdminGivingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGivingRoute: typeof AdminGivingRoute
  AdminHeroSlidesRoute: typeof AdminHeroSlidesRoute
  AdminLeadersRoute: typeof AdminLeadersRoute
  AdminLiveStreamRoute: typeof AdminLiveStreamRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminMinistriesRoute: typeof AdminMinistriesRoute
  AdminPrayerRequestsRoute: typeof AdminPrayerRequestsRoute
  AdminSermonsRoute: typeof AdminSermonsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTestimoniesRoute: typeof AdminTestimoniesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGivingRoute: AdminGivingRoute,
  AdminHeroSlidesRoute: AdminHeroSlidesRoute,
  AdminLeadersRoute: AdminLeadersRoute,
  AdminLiveStreamRoute: AdminLiveStreamRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminMinistriesRoute: AdminMinistriesRoute,
  AdminPrayerRequestsRoute: AdminPrayerRequestsRoute,
  AdminSermonsRoute: AdminSermonsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTestimoniesRoute: AdminTestimoniesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  GivingRoute: GivingRoute,
  LiveRoute: LiveRoute,
  MinistriesRoute: MinistriesRoute,
  PrayerRoute: PrayerRoute,
  SermonsRoute: SermonsRoute,
  TestimoniesRoute: TestimoniesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
